FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["ArenaSportsApi/ArenaSportsApi.csproj", "ArenaSportsApi/"]
RUN dotnet restore "ArenaSportsApi/ArenaSportsApi.csproj"
COPY . .
WORKDIR "/src/ArenaSportsApi"
RUN dotnet build "ArenaSportsApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ArenaSportsApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ArenaSportsApi.dll"]
